language: cpp
compiler:
- gcc
- clang
env:
- POPPLER_VERSION=0.24.0
- POPPLER_VERSION=0.31.0
- POPPLER_VERSION=0.35.0
- POPPLER_VERSION=0.57.0
- POPPLER_VERSION=0.58.0
- POPPLER_VERSION=0.62.0
- POPPLER_VERSION=0.64.0
- POPPLER_VERSION=git
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - autoconf
    - automake
    - djvulibre-bin
    - docbook-xml
    - docbook-xsl
    - fonts-linuxlibertine
    - gettext
    - libdjvulibre-dev
    - libexiv2-dev
    - libfontconfig1-dev
    - libgraphicsmagick++1-dev
    - libopenjpeg-dev
    - libxml2-utils
    - pkg-config
    - python-imaging
    - python-pip
    - python3-pip
    - texlive-base
    - texlive-fonts-recommended
    - texlive-xetex
    - uuid-dev
    - xsltproc
cache: ccache
before_install:
- export PATH=$(echo "$PATH" | tr ':' '\n' | sed -e '/\/opt\/python/d' | tr '\n' ':' | sed 's/::/:/g')
- echo "$PATH" | tr ":" "\n" | grep -w ccache
- last_poppler_release=$(grep -- '^- POPPLER_VERSION=[0-9]' .travis.yml | tail -n1 | cut -d= -f2)
- test -n "$last_poppler_release"
- if [[ $POPPLER_VERSION != $last_poppler_release ]]; then if_lpr=:; fi
- if [[ $POPPLER_VERSION = git ]]; then unless_git=:; else if_git=:; fi
- if [[ $POPPLER_VERSION = git ]] || [[ $POPPLER_VERSION = 0.[6-9]* ]]; then if_autoconf=:; else if_cmake=:; fi
- if [[ $CXX = clang* ]]; then configure_options='--disable-openmp'; fi
install:
- $unless_git wget --no-check-certificate https://poppler.freedesktop.org/poppler-${POPPLER_VERSION}.tar.xz
- $unless_git tar -xvvf poppler-*.tar.*
- $if_git git clone https://anongit.freedesktop.org/git/poppler/poppler.git poppler-git
- pushd poppler-*
- $if_cmake cmake . -DCMAKE_INSTALL_PREFIX="$HOME/.local" -DENABLE_XPDF_HEADERS=ON -DBUILD_GTK_TESTS=OFF -DBUILD_QT4_TESTS=OFF -DBUILD_QT5_TESTS=OFF -DBUILD_CPP_TESTS=OFF -DENABLE_SPLASH=ON -DENABLE_UTILS=OFF -DENABLE_CPP=OFF -DENABLE_GLIB=OFF -DENABLE_QT4=OFF -DENABLE_QT5=OFF -DENABLE_LIBCURL=OFF -DENABLE_ZLIB=OFF -DENABLE_LIBOPENJPEG=unmaintained
- $if_autoconf ./configure --prefix ~/.local --disable-static --enable-xpdf-headers --enable-splash-output --disable-libtiff --disable-zlib --disable-libcurl --disable-libjpeg --disable-libpng --disable-cairo-output --disable-poppler-glib --disable-poppler-qt4 --disable-poppler-cpp --disable-gtk-test --disable-utils --without-x
- make
- make install
- export PKG_CONFIG_PATH=~/.local/lib/pkgconfig/
- export CPATH=~/.local/include/
- export LD_LIBRARY_PATH=~/.local/lib/
- popd
- python3 -m pip install --user img2pdf
- python -m pip install --user nose
- $if_lpr python -m pip install --user docutils
- $if_lpr python -m pip install --user pydiatra pyflakes
before_script:
- private/autogen
script:
- ./configure --prefix ~/.local $configure_options
- make -C tests prepare
- make
- ./pdf2djvu --version
- make test
- $if_lpr private/check-rst
- $if_lpr xmllint --nonet --noout --valid doc/*.xml
- $if_lpr python -m pydiatra tests/
- $if_lpr python -m pyflakes tests/
- $if_lpr make -C doc
- make install
- cd /
- pdf2djvu --version
- export MANPATH=~/.local/share/man MANWIDTH=80
- $if_lpr grep -A 10 -w PDF2DJVU <<<"$(man 1 pdf2djvu)"

# vim:ts=2 sts=2 sw=2 et
