language: cpp
compiler:
- gcc
- clang
env:
- POPPLER_VERSION=0.17.0
- POPPLER_VERSION=0.19.0
- POPPLER_VERSION=0.21.0
- POPPLER_VERSION=0.21.1
- POPPLER_VERSION=0.23.0
- POPPLER_VERSION=0.31.0
- POPPLER_VERSION=0.57.0
- POPPLER_VERSION=0.58.0
- POPPLER_VERSION=0.60.1
matrix:
  exclude:
  # “-fno-check-new” is not supported by clang
  - compiler: clang
    env: POPPLER_VERSION=0.17.0
  - compiler: clang
    env: POPPLER_VERSION=0.19.0
  - compiler: clang
    env: POPPLER_VERSION=0.21.0
  - compiler: clang
    env: POPPLER_VERSION=0.21.1
  - compiler: clang
    env: POPPLER_VERSION=0.23.0
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - autoconf
    - automake
    - djvulibre-bin
    - docbook-xml
    - fonts-linuxlibertine
    - gettext
    - libdjvulibre-dev
    - libexiv2-dev
    - libfontconfig1-dev
    - libgraphicsmagick++1-dev
    - libopenjpeg-dev
    - libxml2-utils
    - pkg-config
    - python-docutils
    - python-imaging
    - python-nose
    - python3-pip
    - texlive-base
    - texlive-fonts-recommended
    - texlive-xetex
    - uuid-dev
cache: ccache
before_install:
- export PATH=$(echo "$PATH" | tr ':' '\n' | sed -e '/\/opt\/python/d' | tr '\n' ':' | sed 's/::/:/g')
- 'echo "$PATH" | tr : "\n" | grep -w ccache'
install:
- if [ -z "${POPPLER_VERSION##0.[3-9]*}" ] || [ -z "${POPPLER_VERSION##0.2[3-9]*}" ]; then POPPLER_COMPRESSION=xz; else POPPLER_COMPRESSION=gz; fi
- wget --no-check-certificate https://poppler.freedesktop.org/poppler-${POPPLER_VERSION}.tar.${POPPLER_COMPRESSION}
- tar -xvvf poppler-*.tar.*
- pushd poppler-*
- |
  if [ -z "${POPPLER_VERSION##0.[6-9]*}" ]; then
    cmake . -DCMAKE_INSTALL_PREFIX="$HOME/opt/poppler" -DENABLE_XPDF_HEADERS=ON -DBUILD_GTK_TESTS=OFF -DBUILD_QT4_TESTS=OFF -DBUILD_QT5_TESTS=OFF -DBUILD_CPP_TESTS=OFF -DENABLE_SPLASH=ON -DENABLE_UTILS=OFF -DENABLE_CPP=OFF -DENABLE_GLIB=OFF -DENABLE_QT4=OFF -DENABLE_QT5=OFF -DENABLE_LIBCURL=OFF -DENABLE_ZLIB=OFF
  else
    ./configure --prefix="$HOME/opt/poppler" --disable-static --enable-xpdf-headers --enable-splash-output --disable-libtiff --disable-zlib --disable-libcurl --disable-libjpeg --disable-libpng --disable-cairo-output --disable-poppler-glib --disable-poppler-qt4 --disable-poppler-cpp --disable-gtk-test --disable-utils --without-x
  fi
- make
- make install
- popd
- python3 -m pip install --user img2pdf
before_script:
- private/autogen
script:
- export PKG_CONFIG_PATH="$HOME/opt/poppler/lib/pkgconfig/"
- export CPATH="$HOME/opt/poppler/include/"
- if [ "$CXX" == clang++ ]; then configure_options='--disable-openmp'; fi
- ./configure $configure_options
- PATH="$PATH:$HOME/.local/bin" make -C tests prepare
- make
- export LD_LIBRARY_PATH="$HOME/opt/poppler/lib/"
- ./pdf2djvu --version
- make test
- private/check-rst
- xmllint --nonet --noout --valid doc/*.xml

# vim:ts=2 sts=2 sw=2 et
